// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlQueries

import (
	"database/sql"
	"time"
)

type AnimeEpsList struct {
	AnimeEpsListID int64
	Animeid        sql.NullInt64
	Episode        string
	CreatedAt      time.Time
}

type AnimeList struct {
	AnimeID   int64
	AnimeName string
	Released  interface{}
	Img       sql.NullString
	Link      string
	CreatedAt time.Time
}

type EpisodesSource struct {
	ID        int64
	AnimeEpID sql.NullInt64
	Source    string
	CreatedAt time.Time
}
